[project]
name = "yt-audio-downloader"
version = "0.1.0"
description = "Download, process, transcribe, and summarize YouTube audio"

dependencies = [
    "yt-dlp",
    "aider-chat",
    "requests",
    "ipykernel",
    "jupyter",
    "notebook",
]
